language: python
python:
  - "3.5"
  - "nightly"
# command to install dependencies
install: "pip install -r requirements-dev.txt"
# command to run tests
script:
  - pylint --rcfile=.pylint.rcfile org/  || true
  - pylint --rcfile=.pylint.rcfile clarin_dspace/  || true
  - pep8 --show-source --show-pep8 --statistics --max-line-length=100  --filename=*.py ./ || true