language: python
python:
  - "2.7"
  - "3.5"

install: "pip install -r requirements-dev.txt"

before_script:
  - pylint --rcfile=.pylint.rcfile shortref/  || true
  - pylint --rcfile=.pylint.rcfile clarindspace/  || true
  - pep8 --show-source --show-pep8 --statistics --max-line-length=100 clarindspace shortref || true

script:
  - nosetests -v ./tests/